### ISSUE TITLE
About Usage

### ISSUE THREAD

**Issue by HoracceFeng** [pikkaay/efficientnet_gpu#1]
Hi @pikkaay ,

Thanks for your share. Are these code modify from the `tensorflow/tpu` version of EfficientNet and can trained either b0 or b4 model? 

Best.

**Comment by pikkaay** [comment]
Hi,
Yes it is.
The modified code is in transfer_learn.ipynb notebook and you can train on all efficientnet versions as well.

**Comment by HoracceFeng** [comment]
Thank you for your reply. I will close this issue.
